---
# Use & for colors in custom names
rewards:
  1: # Can be anything
    type: "item"
    id: 1
    meta: 0
    count: 1
    customName: "Default" # "Default" for the default name
    enchantments:
      - "0:1" # ID:Level
      - "1:1"
      - "2:1"
  2: # Can be anything
    type: "command"
    command: "give {player} 1 1"
    message: "&aYou've received a reward" # & for color

reward-count-min: 1 # The min amount of rewards a player can get.
reward-count-max: 5 # The max amount of rewards a player can get.

chance: 100 # Chance of getting reward
...