---
# Item ID of the reward
# This will permanently override the item
mining-reward-id: 381 # Ender Eye

# Use & for color
prefix: "&8[&a&lMR&r&8] "

# Titles that will be randomized
titles:
  - "Wow!"
  - "Bonkers!"
  - "Cha-Ching!"
  - "Treasure!"
  - "Awesome!"
  - "Nice!"

# Use & for colors in custom names
rewards:
  1: # Can be anything
    type: "item"
    id: 1
    meta: 0
    count: 1
    customName: "Default" # "Default" for the default name
    enchantments:
      - "0:1" # ID:Level
      - "1:1"
      - "2:1"
  2: # Can be anything
    type: "command"
    command: "give {player} 1 1"
    message: "&aYou've received a reward" # & for color

reward-count-min: 1 # The min amount of rewards a player can get.
reward-count-max: 5 # The max amount of rewards a player can get.

chance: 100 # Chance of getting crate for rewards

lengthOfAnimation: 20 # 4 = 1 second
...